name: Build and Push Prometheus LLM Proxy Docker Image

on:
  push:
    tags:
      - "*"
    branches:
      - "FEAT-2_k8s_deploy"

jobs:
  build-and-push-main-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set TAG output
        id: vars
        run: echo "TAG=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          push: true
          tags: emirozbir/prometheus-llm-proxy:v0.0.2-rc-tag








