name: Release Postgresql Connection Manager

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go 1.24.2
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.2
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --config=build/.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.PROMETHEUS_LLM_PROXY_TOKEN }}